INSERT IGNORE INTO categories (name) VALUES
('Fiction'),
('Programming'),
('Fantasy'),
('Dystopian'),
('Science Fiction'),
('Business'),
('Biography'),
('History'),
('Romance');

INSERT IGNORE INTO authors (name) VALUES
('J.K. Rowling'),
('J.R.R. Tolkien'),
('Jane Austen'),
('F. Scott Fitzgerald'),
('George Orwell'),
('Aldous Huxley'),
('Joshua Bloch'),
('Jeannette Walls'),
('Donald Knuth'),
('Jon Duckett'),
('James Clear'),
('Walter Isaacson'),
('Brandon Sanderson'),
('Douglas Adams'),
('Martin Fowler'),
('Robert C. Martin'),
('Erich Gamma'),
('Andy Weir'),
('Frank Herbert'),
('Ashlee Vance'),
('Cal Newport'),
('Eric Ries'),
('Peter Thiel'),
('Harper Lee'),
('Yuval Noah Harari'),
('Tara Westover'),
('Michelle Obama'),
('Anne Frank'),
('George S. Clason'),
('Napoleon Hill'),
('Charles Dickens');

INSERT IGNORE INTO books (title, description, price, stock, image_url, author_id, category_id) VALUES
('Harry Potter and the Sorcerer''s Stone', 'A young wizard discovers his destiny.', 19.99, 30, 'https://picsum.photos/seed/book-01/400/600', (SELECT id FROM authors WHERE name='J.K. Rowling' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('Harry Potter and the Chamber of Secrets', 'Mystery unfolds at Hogwarts during second year.', 20.99, 28, 'https://picsum.photos/seed/book-02/400/600', (SELECT id FROM authors WHERE name='J.K. Rowling' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('The Hobbit', 'Bilbo Baggins embarks on an unexpected quest.', 18.50, 22, 'https://picsum.photos/seed/book-03/400/600', (SELECT id FROM authors WHERE name='J.R.R. Tolkien' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('The Fellowship of the Ring', 'The One Ring begins its long journey.', 21.00, 24, 'https://picsum.photos/seed/book-04/400/600', (SELECT id FROM authors WHERE name='J.R.R. Tolkien' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('The Two Towers', 'The fellowship is broken but the quest continues.', 21.00, 24, 'https://picsum.photos/seed/book-05/400/600', (SELECT id FROM authors WHERE name='J.R.R. Tolkien' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('The Return of the King', 'Final battle for Middle-earth.', 21.00, 24, 'https://picsum.photos/seed/book-06/400/600', (SELECT id FROM authors WHERE name='J.R.R. Tolkien' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('Pride and Prejudice', 'Classic romance and social commentary.', 14.99, 35, 'https://picsum.photos/seed/book-07/400/600', (SELECT id FROM authors WHERE name='Jane Austen' LIMIT 1), (SELECT id FROM categories WHERE name='Romance' LIMIT 1)),
('The Great Gatsby', 'A portrait of ambition and illusion.', 13.99, 26, 'https://picsum.photos/seed/book-08/400/600', (SELECT id FROM authors WHERE name='F. Scott Fitzgerald' LIMIT 1), (SELECT id FROM categories WHERE name='Fiction' LIMIT 1)),
('To Kill a Mockingbird', 'Justice and empathy in the American South.', 15.99, 27, 'https://picsum.photos/seed/book-09/400/600', (SELECT id FROM authors WHERE name='Harper Lee' LIMIT 1), (SELECT id FROM categories WHERE name='Fiction' LIMIT 1)),
('1984', 'A chilling dystopian surveillance state.', 16.50, 20, 'https://picsum.photos/seed/book-10/400/600', (SELECT id FROM authors WHERE name='George Orwell' LIMIT 1), (SELECT id FROM categories WHERE name='Dystopian' LIMIT 1)),
('Brave New World', 'A futuristic society engineered for control.', 16.00, 20, 'https://picsum.photos/seed/book-11/400/600', (SELECT id FROM authors WHERE name='Aldous Huxley' LIMIT 1), (SELECT id FROM categories WHERE name='Dystopian' LIMIT 1)),
('Dune', 'Epic science fiction of politics and prophecy.', 22.99, 18, 'https://picsum.photos/seed/book-12/400/600', (SELECT id FROM authors WHERE name='Frank Herbert' LIMIT 1), (SELECT id FROM categories WHERE name='Science Fiction' LIMIT 1)),
('The Martian', 'An astronaut fights to survive on Mars.', 19.50, 17, 'https://picsum.photos/seed/book-13/400/600', (SELECT id FROM authors WHERE name='Andy Weir' LIMIT 1), (SELECT id FROM categories WHERE name='Science Fiction' LIMIT 1)),
('Project Hail Mary', 'A lone mission to save humanity.', 23.99, 19, 'https://picsum.photos/seed/book-14/400/600', (SELECT id FROM authors WHERE name='Andy Weir' LIMIT 1), (SELECT id FROM categories WHERE name='Science Fiction' LIMIT 1)),
('The Hitchhiker''s Guide to the Galaxy', 'Absurd and brilliant interstellar comedy.', 17.99, 21, 'https://picsum.photos/seed/book-15/400/600', (SELECT id FROM authors WHERE name='Douglas Adams' LIMIT 1), (SELECT id FROM categories WHERE name='Science Fiction' LIMIT 1)),
('Clean Code', 'Practical guide to writing maintainable code.', 29.99, 25, 'https://picsum.photos/seed/book-16/400/600', (SELECT id FROM authors WHERE name='Robert C. Martin' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('Clean Architecture', 'Principles for building long-lasting systems.', 31.99, 23, 'https://picsum.photos/seed/book-17/400/600', (SELECT id FROM authors WHERE name='Robert C. Martin' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('Refactoring', 'Improve existing code without changing behavior.', 34.99, 20, 'https://picsum.photos/seed/book-18/400/600', (SELECT id FROM authors WHERE name='Martin Fowler' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('Effective Java', 'Best practices for modern Java development.', 32.99, 22, 'https://picsum.photos/seed/book-19/400/600', (SELECT id FROM authors WHERE name='Joshua Bloch' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('Design Patterns', 'Foundational object-oriented design patterns.', 33.50, 18, 'https://picsum.photos/seed/book-20/400/600', (SELECT id FROM authors WHERE name='Erich Gamma' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('Atomic Habits', 'Small habits that produce remarkable results.', 18.99, 32, 'https://picsum.photos/seed/book-21/400/600', (SELECT id FROM authors WHERE name='James Clear' LIMIT 1), (SELECT id FROM categories WHERE name='Business' LIMIT 1)),
('Deep Work', 'Focus strategies for high-value output.', 17.99, 31, 'https://picsum.photos/seed/book-22/400/600', (SELECT id FROM authors WHERE name='Cal Newport' LIMIT 1), (SELECT id FROM categories WHERE name='Business' LIMIT 1)),
('The Lean Startup', 'Validated learning for startups.', 20.99, 30, 'https://picsum.photos/seed/book-23/400/600', (SELECT id FROM authors WHERE name='Eric Ries' LIMIT 1), (SELECT id FROM categories WHERE name='Business' LIMIT 1)),
('Zero to One', 'Building companies that create new value.', 19.99, 30, 'https://picsum.photos/seed/book-24/400/600', (SELECT id FROM authors WHERE name='Peter Thiel' LIMIT 1), (SELECT id FROM categories WHERE name='Business' LIMIT 1)),
('The Richest Man in Babylon', 'Timeless lessons on personal finance.', 12.99, 34, 'https://picsum.photos/seed/book-25/400/600', (SELECT id FROM authors WHERE name='George S. Clason' LIMIT 1), (SELECT id FROM categories WHERE name='Business' LIMIT 1)),
('Think and Grow Rich', 'Classic mindset and achievement principles.', 13.99, 33, 'https://picsum.photos/seed/book-26/400/600', (SELECT id FROM authors WHERE name='Napoleon Hill' LIMIT 1), (SELECT id FROM categories WHERE name='Business' LIMIT 1)),
('Sapiens', 'A brief history of humankind.', 24.99, 20, 'https://picsum.photos/seed/book-27/400/600', (SELECT id FROM authors WHERE name='Yuval Noah Harari' LIMIT 1), (SELECT id FROM categories WHERE name='History' LIMIT 1)),
('Educated', 'A memoir about resilience and learning.', 18.50, 22, 'https://picsum.photos/seed/book-28/400/600', (SELECT id FROM authors WHERE name='Tara Westover' LIMIT 1), (SELECT id FROM categories WHERE name='Biography' LIMIT 1)),
('Becoming', 'Memoir of former First Lady Michelle Obama.', 21.50, 21, 'https://picsum.photos/seed/book-29/400/600', (SELECT id FROM authors WHERE name='Michelle Obama' LIMIT 1), (SELECT id FROM categories WHERE name='Biography' LIMIT 1)),
('The Diary of a Young Girl', 'Personal account of life during war.', 14.50, 25, 'https://picsum.photos/seed/book-30/400/600', (SELECT id FROM authors WHERE name='Anne Frank' LIMIT 1), (SELECT id FROM categories WHERE name='History' LIMIT 1)),
('The Art of Computer Programming', 'Comprehensive algorithms and programming analysis.', 89.99, 10, 'https://picsum.photos/seed/book-31/400/600', (SELECT id FROM authors WHERE name='Donald Knuth' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('HTML and CSS: Design and Build Websites', 'Visual guide to web fundamentals.', 25.99, 18, 'https://picsum.photos/seed/book-32/400/600', (SELECT id FROM authors WHERE name='Jon Duckett' LIMIT 1), (SELECT id FROM categories WHERE name='Programming' LIMIT 1)),
('Mistborn: The Final Empire', 'Heist-style fantasy with a unique magic system.', 18.99, 19, 'https://picsum.photos/seed/book-33/400/600', (SELECT id FROM authors WHERE name='Brandon Sanderson' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('Steve Jobs', 'Biography of Apple''s co-founder.', 22.99, 16, 'https://picsum.photos/seed/book-34/400/600', (SELECT id FROM authors WHERE name='Walter Isaacson' LIMIT 1), (SELECT id FROM categories WHERE name='Biography' LIMIT 1)),
('Elon Musk', 'Story of the entrepreneur behind Tesla and SpaceX.', 21.99, 16, 'https://picsum.photos/seed/book-35/400/600', (SELECT id FROM authors WHERE name='Ashlee Vance' LIMIT 1), (SELECT id FROM categories WHERE name='Biography' LIMIT 1)),
('The Glass Castle', 'Memoir of an unconventional upbringing.', 17.99, 15, 'https://picsum.photos/seed/book-36/400/600', (SELECT id FROM authors WHERE name='Jeannette Walls' LIMIT 1), (SELECT id FROM categories WHERE name='Biography' LIMIT 1)),
('Animal Farm', 'Political allegory on revolution and power.', 12.99, 28, 'https://picsum.photos/seed/book-37/400/600', (SELECT id FROM authors WHERE name='George Orwell' LIMIT 1), (SELECT id FROM categories WHERE name='Fiction' LIMIT 1)),
('Fantastic Beasts and Where to Find Them', 'Companion book from the wizarding world.', 16.99, 20, 'https://picsum.photos/seed/book-38/400/600', (SELECT id FROM authors WHERE name='J.K. Rowling' LIMIT 1), (SELECT id FROM categories WHERE name='Fantasy' LIMIT 1)),
('A Tale of Two Cities', 'Historical novel set in London and Paris.', 13.99, 14, 'https://picsum.photos/seed/book-39/400/600', (SELECT id FROM authors WHERE name='Charles Dickens' LIMIT 1), (SELECT id FROM categories WHERE name='Fiction' LIMIT 1)),
('Sense and Sensibility', 'Austen''s story of love, logic, and social pressure.', 14.25, 18, 'https://picsum.photos/seed/book-40/400/600', (SELECT id FROM authors WHERE name='Jane Austen' LIMIT 1), (SELECT id FROM categories WHERE name='Romance' LIMIT 1));
